#!/bin/bash

#This script creates a KVM image disk of n size - does not attach it
#Set defaults (for now):
# default storage location /mnt/sdb/vm_store/default01
# default image format = raw

img_location=/mnt/sdb/vm_store/default01
vms_all=$( virsh list --all --name )

echo ""
echo -e "Welcome to the KVM volume creator and mounting tool!"
echo -e "Disk will be created at /mnt/sdb/vm_store/default01 by default"
echo -e "Only enter integer for disk size (GB)" 
echo -e "Please follow the convention for img names: <vm attached to>-<purpose>-<size>\n"
read -p "Enter image size: " img_size
read -p "Enter image name: " img_name
printf "Creating "$img_name" at "$img_location"\n"
read -p "Confirm? (y/n)...? " img_confirmation

#Creates image after confirmation from $img_confirmation
if [[ $img_confirmation = "y" ]]; then
	echo "Creating image..."
	qemu-img create -f raw "$img_location"/"$img_name" ${img_size}G && 
	echo "Image $img_name has been sucessfuly created!" 
else
	printf "Goodbye\n"
    exit 0
fi

