#!/bin/bash

#This script creates a KVM image disk if n size and attaches it to any running vm
#Set defaults (for now)
# default storage location /mnt/sdb/vm_store/default01
# default image format = raw

img_location=/mnt/sdb/vm_store/default01

echo ""
echo -e "Welcome to the KVM img creator and mounting tool!"
echo -e "Disk will be created at /mnt/sdb/vm_store/default01 by default"
echo -e "Please specify only enter a number, size will default to G"
echo -e "Please follow the convention for img names: <vm attached to>-<purpose>-<size>\n"
read -p "Enter image size: " img_size
read -p "Enter image name: " img_name
read -p "Enter target VM name, or press "l" to list all VMs: " target_vm

if [[ $target_vm = "l" ]]; then
	virsh list --all --name
	read -p "Please select one of the VM's listed: " target_vm
else
	echo "Image: $img_name of Size: $img_size will be \
created at "$img_location"/"$img_name" and attached to $target_vm"
fi

read -p "Create image? (y/n)" img_confirmation

if [[ $img_confirmation = "y" ]]; then
	echo "Creating image..."
	qemu-img create -f raw "$img_location"/"$img_name" $img_size"G" && 
	echo "Image $img_name has been sucessfuly created!" 
fi

read -p "Would you like to attach $img_name to $target_vm? (y/n)" img_confirmation

if [[ $img_confirmation = y ]]; then
	read -p "enter target block name: " blk_name
	echo "Attaching $img_name to $target_vm..."
	virsh attach-disk $target_vm "$img_location"/"$img_name" $blk_name --persistent &&
	echo "Image $img_name has been sucsessfuly attached to $target_vm"
fi

