#!/bin/bash

#Select vm to mount img to 
printf "Select VM that disk will be mounted to: \n"
select _vm in $( virsh list --all --name ); do
    break
done

#List avaiable disks for _vm
_img_pth=/cloud/storage/${_vm}-mounts
printf "Select disk to mount to $_vm: \n"
select _img in $( ls $_img_pth ); do
    break
done

printf "Please select a block device name, the below cannot be used: \n"
/root/VM_scripts/tools/BLOCKfinder $_vm
read -p ": " _blk

#Runs command to mount drive _vm
virsh attach-disk $_vm $_img_pth/$_img $_blk --persistent || printf "Error!"

