#!/bin/bash 

#testing while loop to keep asking for correct input 

#pseudo code:
#while img_name not in img_list
    #input img_name
    # img_name in img_list
    #then echo something else
read -p "Enter vm name: " vm_name
vm_list=$( virsh list --all --name )

while [[ !( "$vm_list" =~ "$vm_name" ) ]]
do
    printf "Virtual Machine not found!\n"
    printf "Please select one of the following: \n"
    printf "$vm_list"
    read -p "please try again: " vm_name
    if [[ "$vm_list" =~ "$vm_name" ]];then
        break
    fi
done
     
