#!/bin/bash 

#custom tool that can be ran to ensure that VM input by user is real.
#Command can be ran as #command #parameter
#$1 refers to the parameter being passed as vm_name in main mk_drive file

cmd_virsh=$( virsh list --all --name )

[[ " $cmd_virsh " =~ "$1" ]] && echo "true" || echo "false"
